# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
    # has_position_limits: true
    # max_position: !degrees -80
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
    # has_position_limits: true
    # max_position: !degrees -60
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    max_position: !degrees -110.0
    min_position: !degrees -240.0
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    max_position: !degrees -45.0
    min_position: !degrees -105.0
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    max_position: !degrees 110.0
    min_position: !degrees 70.0
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
    has_position_limits: true
    max_position: !degrees 350
    min_position: !degrees -350